### ISSUE TITLE
DNS Cog: Checking the validity of salesloft's SPF record does not show any results

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-dns#5]
Steps to Reproduce:
1. in the cmd, type crank cog:step automatoninc/dns
2. Select the step: Check the validity of a domain's SPF record.
3. Enter salesloft.com as the domain name.
3. Observe after it finishes running

Note: Encountered it on the ff domains:
salesloft.com
microsoft.com

![image](https://user-images.githubusercontent.com/54615569/65857156-d5510600-e395-11e9-96a0-aaea3258d927.png)

**Comment by roanlibelo** [comment]
![image](https://user-images.githubusercontent.com/54615569/65850929-7aaeae80-e383-11e9-8ed0-a850cf7f5f00.png)

**Comment by iamEAP** [comment]
@roanlibelo (cc: @saludangelito): I ran into a similar issue today and put in a fix, but I couldn't reproduce this issue using either domain before or after the fix.

@roanlibelo can you try again using...

```shell-session
crank cog:install automatoninc/dns:dev-v36 --force --ignore-auth
```

**Comment by roanlibelo** [comment]
Upon verifying, issue no longer occur. Closing this ticket.
